replsetname:  "{{ inventory_hostname.split('_')[0] }}"
bindip: "{{ ansible_facts['default_ipv4']['address'] }}"
# server_port: 27017
dbpath: /var/lib/mongodb
logpath: /var/log/mongodb/mongod.log
shardmode: shardsvr
root_user_pass: saeed
superuser_pass: saeed
authenticationMechanisms: SCRAM-SHA-256