---

- hosts: all
  become: true
  pre_tasks:


  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
      

- hosts: all
  become: true
  gather_facts: yes
  vars_prompt:
  - name: "work_pass"
    prompt: "Please enter the password for the workstation"
    private: yes
  - name: "shardsvr_port"
    prompt: "Please enter the port for the shardsvr Mongo Server"
    private: no
    default: 27017
  - name: "configsvr_port"
    prompt: "Please enter the port for the confsvr Mongo Server"
    private: no
    default: 27018
  - name: "confsvr"
    prompt: "Please enter group name for confsvr"
    private: no
    default: shardsvr
  vars:
    exclude_groups:
      - workstations
      - "{{confsvr}}"
    target_group: "{{confsvr}}"  # Specify the group to target
  tasks:
  - name: run create replica in shard servers
    vars:
      server_port: "{{shardsvr_port}}"
    include_role:
      name: db_servers_shard
      tasks_from: shardsvr
    when: exclude_groups | intersect(group_names) | length == 0
  - name: run create replica in config servers
    vars:
      server_port: "{{configsvr_port}}"
      exclude_groups:
        - workstations
        - "{{confsvr}}"
      target_group: "{{confsvr}}"  # Specify the group to target
    include_role:
      name: db_servers_shard
      tasks_from: configsvr
    when: inventory_hostname in groups[target_group]