- hosts: rs0,rs1
  become: true
  vars_prompt:
  - name: "mongohost"
    prompt: "Please enter the ip of the Mongo Server"
    private: no
    default: 
  - name: "mongoport"
    prompt: "Please enter the port of the Mongo Server"
    private: no
    default: 27017
  - name: "username"
    prompt: "Please enter the username of the Mongo Server"
    private: no
    default:
  - name: "password"
    prompt: "Please enter the password of the Mongo Server"
    private: yes
    default:

  - name: "databasename"
    prompt: "Please enter the databasename of the Mongo Server"
    private: no
    default: admin

  - name: "backupPath"
    prompt: "Please enter the backupPath for mongo dump"
    private: no
    default: dump

  - name: "auth_db"
    prompt: "Please enter the auth_db for mongo dump"
    private: no
    default: admin
  roles:
    - mongodump