---

# - hosts: all
#   become: true
#   pre_tasks:


#   - name: update repository index (Ubuntu)
#     tags: always
#     apt:
#       update_cache: yes
#     changed_when: false
#     when: ansible_distribution == "Ubuntu"

# - hosts: all
#   become: true
#   roles:
#     - base
      

- hosts: rs0,rs1
  become: true
  roles:
    - db_servers_repl

- hosts: rs0,rs1
  become: true
  pre_tasks:
  - name: change servermode
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^#sharding:'
      line: "sharding:"
  - name: add shard servermode
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^#\s*clusterRole:'
      line: "  clusterRole: {{ shardmode }}"
  - name: start mongo server
    service: name=mongod state=restarted enabled=true  


- hosts: rs3
  become: true
  roles:
    - db_servers_shard

- hosts: rs2
  become: true
  vars_prompt:
  - name: "mongos_port"
    prompt: "Please enter the port for the Mongo Server"
    private: no
    default: 27017
  pre_tasks:
  - name: create user for mongos
    community.mongodb.mongodb_shell:
      login_host: "{{ ansible_host }}"
      login_port: "{{ mongosport }}"
      db: "admin"
      eval: "db.createUser( { user: \"root\", pwd: \"saeed\", roles: [ { role: \"root\", db: \"admin\" }] } )"

  - name: enable security for mongos
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^#security:'
      line: "security:"


  - name: change authorization mode
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^#\s*authorization: \"disabled\"'
      line: "  authorization: \"enabled\""

  - name: add key in mongos config
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^#\s*keyFile: /var/lib/mongodb/keyfile'
      line: "  keyFile: /var/lib/mongodb/keyfile"
  - name: restart mongos
    service: name=mongos state=restarted enabled=true    

- hosts: all
  become: true
  roles:
    - authentication