# - name: Create the role that allows any action on any resource.
#   community.mongodb.mongodb_shell:
#     login_host: "{{ ansible_host }}"
#     login_port: "{{ server_port }}"
#     login_user: "{{rootuser}}"
#     login_password: "{{rootpass}}"
#     db: "admin"
#     eval: "db.createRole({ \"role\": \"pbmAnyAction\",\"privileges\": [{ \"resource\": { \"anyResource\": true },\"actions\": [ \"anyAction\" ]}],\"roles\": []})"
#   ignore_errors: yes


# - name: Create the user and assign the role you created to it.
#   community.mongodb.mongodb_shell:
#     login_host: "{{ ansible_host }}"
#     login_port: "{{ server_port }}"
#     login_user: "{{rootuser}}"
#     login_password: "{{rootpass}}"
#     db: "admin"
#     eval: "db.createUser({user: \"{{pbmuser}}\",\"pwd\": \"{{pbmpass}}\",\"roles\" : [{ \"db\":\"admin\", \"role\":\"readWrite\",\"collection\":\"\" },{ \"db\":\"admin\", \"role\":\"backup\" },{ \"db\":\"admin\", \"role\":\"clusterMonitor\" },{ \"db\":\"admin\", \"role\":\"restore\" },{ \"db\":\"admin\", \"role\":\"pbmAnyAction\" }]})"
#   ignore_errors: yes



- name: Create pbm config for s3 storage
  template:
    src: pbm_storage_s3.j2
    dest: /etc/pbm-storage.conf

- name: Edit the environment file /etc/default/pbm-agent
  template:
    src: pbm_agent_vars.j2
    dest:  /etc/default/pbm-agent